### ISSUE TITLE
Could not prepare directory: objectbox (30)

### ISSUE THREAD

**Issue by aarajput** [objectbox/objectbox-dart#130]
I am getting below error when i try to call `Store(getObjectBoxModel());`

<img width="901" alt="Screen Shot 2020-10-14 at 11 37 44 AM" src="https://user-images.githubusercontent.com/16102514/95952512-b216be80-0e11-11eb-9036-daffceb6053e.png">

**Comment by aarajput** [comment]
This is my pubspec.yaml

```
name: App
description: Flutter application to show app to users.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  wc_form_validators: ^0.1.1
  cached_network_image: ^2.3.1
  after_layout: ^1.0.7+2
  dio: ^3.0.10
  intl: ^0.16.1
  bloc: ^6.0.3
  flutter_bloc: ^6.0.6
  hydrated_bloc: ^6.0.1
  animations: ^1.1.2
  page_transition: ^1.1.6
  flutter_i18n: ^0.20.0
  flutter_translate_annotations: ^1.0.0
  dotted_border: ^1.0.6
  package_info: ^0.4.3
  device_info: ^0.4.2+8
  shimmer: ^1.1.1
  timeago: ^2.0.27
  flutter_facebook_auth: ^0.3.2
  wc_flutter_share: ^0.2.2
  url_launcher: ^5.7.2
  youtube_player_flutter: ^7.0.0+7
  flutter_svg: ^0.19.0
  flutter_html:
    git: https://github.com/aarajput/flutter_html.git
  webview_flutter: ^1.0.0
  shared_preferences: ^0.5.12
  random_string: ^2.1.0
  sign_in_with_apple: ^2.5.2
  google_sign_in: ^4.5.4
  file_picker: ^2.0.7
  image_crop: ^0.3.3
  objectbox: ^0.8.0
  objectbox_flutter_libs: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.1.0
  flutter_translate_gen: ^1.2.1
  objectbox_generator: ^0.8.0
  build_runner: ^1.10.3

dependency_overrides:
  analyzer: 0.40.4

flutter:
  uses-material-design: true
```
