### ISSUE TITLE
Final fields can't be stored

### ISSUE THREAD

**Issue by Abhilash-Chandran** [objectbox/objectbox-dart#193]
**Description**
The scenario is adapting an existing model class to be compatible with ObjectBox. Assume the following `ToDo.dart` file which represents the model of `ToDo` item. Existing model already uses the reserved keyword `id` as a `String id` for another form of backend store such as Hive or InMemory list. Now to adapt this model to be compatible with ObjectBox terminology, I created a new field called `oboxId` with the `@Id` annottation.

**ToDo.dart**
```dart
import 'package:flutter_todo/commons/backend/base_store.dart';
import 'package:meta/meta.dart';
import 'package:objectbox/objectbox.dart';
import 'package:uuid/uuid.dart';

@Entity()

/// Model class to hold the ToDo Object.
class ToDo {
  /// Unique id of this todo to store in backend.
  /// Already used in Hive and InMemory lists.
  final String id;

  /// Id specifically required for ObjectBox, which must be of type int.
  @Id()
  int oboxId;

  /// Description of this todo.
  String description;

  /// A flag to denote if the to activity is complete
  bool completed;

  /// Due Date for this todo.
  DateTime dueDate;

  /// id of the user who created this todo.
  String userId;

  ToDo({
    @required this.description,
    this.dueDate,
    this.completed = false,
    @required this.userId,
  }) : id = Uuid().v4(); // Initializes id with a unique value.

  @override
  String toString() =>
      'Todo of user $userId with description $description and completed $completed';

  @override
  bool operator ==(o) =>
      o is ToDo &&
      o.description == description &&
      o.completed == completed &&
      o.dueDate == dueDate &&
      o.id == id &&
      o.oboxId == oboxId;

  @override
  int get hashCode =>
      description.hashCode ^
      userId.hashCode ^
      completed.hashCode ^
      dueDate.hashCode ^
      oboxId.hashCode;
}

```

**Basic info (please complete the following information):**
 - ObjectBox Dart version: [e.g. 0.7.0, latest version?]
 - Flutter/Dart SDK: [e.g. 1.20.0, latest version?]
 - Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always]
 - Device: [e.g. Galaxy S20]
 - OS: [e.g. Android 10]

**To Reproduce**
1. Use the `ToDo.dart` as model class.
2. Run `flutter pub run build_runner build`
3. Then try to write a query in following format.

```dart
@override
  Future<ToDo> get(String id) async {
    final query = objBox.query(ToDo_.id.equals(id)).build(); // compiler throws error stating id is not  present in `ToDo_` type.
    
  }
```

**Expected behavior**
It is expected that the `id` field is still available for querying as it is required to fulfill already existing contracts in the code base.

**Additional Information**
<details>
<summary>pubspec.yaml</summary>

```yml
name: flutter_command_todo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_command: ^0.9.3
  get_it: ^5.0.6
  uuid: ^2.2.2
  objectbox: ^0.11.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  objectbox_generator: any

flutter:
  uses-material-design: true
```
</details>

------

**Flutter information**

<details>
<summary>flutter doctor</summary>

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.18363.1316],
    locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!
</details>
