### ISSUE TITLE
Could not begin read transaction (another read transaction is still active on this thread)

### ISSUE THREAD

**Issue by darshansatra1** [objectbox/objectbox-dart#288]
So I'm running a foreground service using the plugin [**flutter_foreground_task**](https://pub.dev/packages/flutter_foreground_task). Before I was using Hive DB, but since the **foreground service** creates a new isolate I was not able to access the same box in the main isolate, and other isolates since Hive does not support **multi-threading** so I tried Object Box. It was working awesome and the main isolate was able to see the changes made in other isolates. But the issue began when I found out that Read operations throw an error when another block accesses(Write/Read) the box at the same time. I read the documentation and it says there can be more than one reader, however it was not the case while I was running the foreground service. 

### Basic info:
- ObjectBox version: ^1.1.1
- Flutter/Dart SDK: 2.2.4-0.0.pre.1 
- Null-safety enabled: yes
- Reproducibility: always
- OS: Windows
- Device/Emulator: OnePlus Nord
 
* `flutter doctor -v`
```
[√] Flutter (Channel stable, 2.2.4-0.0.pre.1, on Microsoft Windows [Version 10.0.19041.1110], locale en-IN)
    • Flutter version 2.2.4-0.0.pre.1 at C:\src\flutter
    • Framework revision a34a20c34d (3 weeks ago), 2021-07-04 14:41:40 +0530
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Darshan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Darshan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • AC2001 (mobile) • 4f0ec2e7 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!
``` 
### Code
```
@override
List<HealthDataModel> fetchAllHealthData() {
  try {
    if (healthDataBox == null) return [];
    return healthDataBox?.getAll() ?? [];
  } catch (e) {
    print(e);
    return [];
  }
}
```
  
- pubspec.yaml.
```
name: health
description: 

publish_to: "none"

version: 1.0.5+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  background_fetch: ^1.0.0
  flutter_foreground_task: ^2.0.4
  objectbox: ^1.1.1
  objectbox_flutter_libs: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
  flutter_native_splash: ^1.1.8+4
  objectbox_generator: ^1.1.1

flutter_native_splash:
  color: "#F8F8FC"
  image: assets/images/splash screen icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 
  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf 

```
- Affected entity classes. Although this error happens randomly for all entity

```
import 'package:objectbox/objectbox.dart';

@Entity()
class HealthDataModel {
  @Id()
  int id;
  @Property(type: PropertyType.date)
  DateTime? date;
  int? baseStep;
  int? steps; 
  HealthDataModel({
    this.id = 0,
    this.date,
    this.baseStep,
    this.steps, 
  });
}

```  

### Logs, stack traces

```
I/flutter (31054): ObjectBoxException: failed to create transaction: 10199 Could not begin read transaction (another read transaction is still active on this thread)
E/Box     (31054): Storage error (code -30783)
```

### Additional context

- Is there anything special about your app?

It tracks your steps even when the app is killed.

- May transactions or multi-threading play a role?

Yes, isolates are being used that's why multi-threading is required.

- Did you find any workarounds to prevent the issue?

- No
