### ISSUE TITLE
Incompatible with freezed

### ISSUE THREAD

**Issue by NitelPhyoe** [objectbox/objectbox-dart#306]
I use flutter: 2.2.3 . Everything fine with **ObjectBox** until i add **Freezed**

``` yaml
#pubspec.yaml
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed: ^0.14.5
  get: ^4.3.8
  objectbox: ^1.1.1
  objectbox_flutter_libs: ^1.1.1
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.14.3
  objectbox_generator: ^1.1.1
```

The Error is
```console
[myapp] flutter pub get
Running "flutter pub get" in myapp...                          
Because no versions of objectbox_generator match >1.1.1 <2.0.0 and objectbox_generator 1.1.1 depends on analyzer ^1.1.0, objectbox_generator ^1.1.1 requires analyzer ^1.1.0.

And because freezed >=0.14.3 depends on analyzer ^2.0.0, objectbox_generator ^1.1.1 is incompatible with freezed >=0.14.3.

So, because myapp depends on both freezed ^0.14.5 and objectbox_generator ^1.1.1, version solving failed.
pub get failed (1; So, because myapp depends on both freezed ^0.14.5 and objectbox_generator ^1.1.1, version solving failed.)
exit code 1
```
