### ISSUE TITLE
Allow declaring directory for generated files

### ISSUE THREAD

**Issue by tomwyr** [objectbox/objectbox-dart#312]
`objectbox-model.json` and `objectbox.g.dart` are generated in _lib_ directory and there's no way of changing it which is inconvenient if you follow some pattern when structuring your project files. Allow ObjectBox users to adjust it in `build.yaml` configuration e.g.:
```
targets:
  $default:
    builders:
      objectbox:
        options:
          output_dir: lib/generated/or/wherever/you/want/it/to/be
```

**Comment by buehler** [comment]
Just encountered the same problem. This would definitely be a great addition to the generator! Otherwise the package is one of the better (if not best) storage possibilities in flutter. Currently we use a makefile to move the files where we want them, but it would definitely be better to have a config for this sort of matter (like `flutter_intl` or the sort)

**Comment by greenrobot-team** [comment]
This feature is now available in the `1.4.0-dev.0` preview release. We welcome your feedback!

To set a custom output directory, add something like the following to `pubspec.yaml` of the desired package:
```yaml
objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: custom
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other
```
