### ISSUE TITLE
Unable to run on linux

### ISSUE THREAD

**Issue by lil5** [objectbox/objectbox-dart#317]
A clear and concise problem description:
I have tried to add objectbox to my project, but just having objectbox in my dependencies is already enough to trigger an error. 

This error is that CMake version is not up to date enough (requires 3.11 or higher) and perceives an installed version of `3.10.2`.  This is strange as my installed version is `3.16.3` which fits the requirement.

The project I am running this on is a flutter project  where the `flutter run` command uses `linux-x64` as device a.k.a. (desktop).

Flutter is installed using `snap`. 

> **Speculation**
> I fear that snap provides a different version of CMake.

### Basic info (please complete the following information):

- ObjectBox version: 1.2.0
- Flutter/Dart SDK: 2.5.0
- Null-safety enabled: yes
- Reproducibility: always
- OS: Linux mint 20.2 x86_64, Kernel: 5.4.0-86-generic
- Device/Emulator: linux-x64

### Steps to reproduce

1. Install Linux mint or Ubuntu 20.10 derivative
2. Install flutter using snap
3. Create a project
4. Add ObjectBox as per examples of ObjectBox-flutter to dependencies

### Expected behavior

Project still works

### Code

```yaml
dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.2.0
  objectbox_flutter_libs: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter
```

### Logs, stack traces

```log
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
CMake Error at flutter/ephemeral/.plugin_symlinks/objectbox_flutter_libs/linux/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 3.10.2


Exception: Unable to generate build files
Exited (sigterm)
```

### Additional context

```log
$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
