### ISSUE TITLE
ToMany is not not overridden on put of main Entity

### ISSUE THREAD

**Issue by jlnrrg** [objectbox/objectbox-dart#326]
I have an Entity (`GameDto`) which has a `ToMany` relation to another entity (`RuleDto`).
If I put the `GameDto` with updated `ToMany` relation, everything works wonders if I just added new values.
Once I put the `GameDto` with less `RuleDto` in the `ToMany` than before, the change is not written.
This could be by intended design, or a bug, so I am not sure how to address this.

### Basic info (please complete the following information):

- ObjectBox version: 1.2.0
- Flutter/Dart SDK: 2.5.3/ 2.14.4
- Null-safety enabled: yes
- Reproducibility: always
- OS: Ubuntu 20.04.3 LTS
- Device/Emulator: Pixel 2 API 30 (android-x86 emulator)

### Steps to reproduce

1. Create a few RuleDto
2. Watch GameDto with id 1
2. Put GameDto (id = 1) with 2 RuleDto
3. Put GameDto with 1 RuleDto
4. Watch delivers new GameDto, but still with 2 RuleDto

### Expected behavior
When I put an Entity (GameDto) with less ToMany relation than saved in the DB the association should be resolved.

### Code
_Entity classes were simplified for this issue._
<details>
<summary>Pubspec.yaml</summary>

```yaml
name: name
description: A new Flutter project.

publish_to: "none"

version: 1.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_icon_button: ^1.0.2
  animated_search_bar: ^2.0.0
  auto_route: ^3.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  dartx: ^0.7.1
  dartz: ^0.10.0
  drag_and_drop_lists: ^0.3.2
  easy_localization: ^3.0.0
  expandable: ^5.0.1
  expandable_page_view: ^1.0.7
  flex_color_picker: ^2.1.2
  flex_color_scheme: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_font_picker: ^0.3.0
  flutter_hooks: ^0.18.0
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^4.4.0+2
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.15.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  icon_picker: ^2.0.1
  json_annotation: ^4.3.0
  line_icons: ^2.0.1
  linked_scroll_controller: ^0.2.0
  material_design_icons_flutter: null
  material_floating_search_bar: ^0.3.4
  number_selection: ^1.0.0
  numberpicker: ^2.1.1
  objectbox: ^1.2.0
  objectbox_flutter_libs: ^1.2.0
  package_info_plus: ^1.2.1
  path_provider: ^2.0.5
  separated_column: ^2.0.0
  separated_row: ^2.0.0
  shared_preferences: ^2.0.8
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  hive_generator: ^1.1.1
  json_serializable: ^6.0.0
  objectbox_generator: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
```

</details>

<details>
<summary>GameDto</summary>

```dart
@Entity()
class GameDto {
  GameDto({
    required this.id,
    required this.ruleSet,
  });
  
  
  factory GameDto.fromDomain(Game g) {
    final gameDto = GameDto(
      id: g.id ?? 0, //? 0 for new entry
      ruleSet:
          ToMany(items: g.ruleSet.map((e) => RuleDto.fromDomain(e)).toList()),
    );
    return gameDto;
  }
  
  @Id()
  int id;
  final ToMany<RuleDto> ruleSet;
  
  Game toDomain() {
  
    final game = Game(
      id: id,
      ruleSet: List.from(ruleSet.map<Rule>((e) => e.toDomain())),
    );

    return game;
  }
}
```

</details>
<details>
<summary>RuleDto</summary>

```dart

@Entity()
class RuleDto {
  RuleDto({
    required this.id,
  });
    
  factory RuleDto.fromDomain(Rule rule) {
    return RuleDto(
      id: rule.id ?? 0, //? 0 for new entry
    );
  }
  
  @Id()
  int id;
  
  Rule toDomain() {
    return Rule(
      id: id,
    );
  }
}
```
</details>
