### ISSUE TITLE
Windows ERROR : Storage error "No such file or directory" (code 2)

### ISSUE THREAD

**Issue by hyderali0889** [objectbox/objectbox-dart#447]
I am starting to learn object box with flutter but it seems that Object Box failed to create a store because it could not prepare the directory

> Unhandled Exception: ObjectBoxException: failed to create store: 10199 Could not prepare directory: C:\Users\Hayder Ali\Documents/objectbox (2)

and throws Storage error

> Storage error "No such file or directory" (code 2)

I've followed the instructions from [Object Box Guide](https://docs.objectbox.io/getting-started).

My Helper File Code is

```
// ignore_for_file: file_names

import '../objectbox.g.dart'; // created by `flutter pub run build_runner build`

class ObjectBox {
  /// The Store of this app.
  late final Store store;

  ObjectBox._create(this.store) {
    // Add any additional setup code, e.g. build queries.
  }

  /// Create an instance of ObjectBox to use throughout the app.
  static Future<ObjectBox> create() async {
    // Future<Store> openStore() {...} is defined in the generated objectbox.g.dart
    final store = await openStore();
    return ObjectBox._create(store);
  }
}
```
and the pubspec.yaml file is

```
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.6.0
  objectbox_flutter_libs: any
  local_auth: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true
```
and the main.dart file is

```
import 'package:flutter/material.dart';
import 'package:obj_box/Screens/Home_Screen.dart';
import 'Helper/ObjectBoxHelper.dart';

late ObjectBox objectBox;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  objectBox = await ObjectBox.create();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}
```

The model file is 

```
// ignore_for_file: file_names
import 'package:objectbox/objectbox.dart';

@Entity()
class User {

  String email;
  String password;
  int id;

  User({this.id = 0, required this.email, required this.password});
}
```

I am not yet using the box anywhere it just fails to start. Any help. Haven't tested the app on any other platform.
