### ISSUE TITLE
objectbox_flutter_libs_plugin.dll is flagged as infected

### ISSUE THREAD

**Issue by Mangiang** [objectbox/objectbox-dart#462]
### Basic info:

- ObjectBox version: ^1.6.2
- Fluttert SDK: 3.0.5
- Null-safety enabled: yes
- Reproducibility: always
- OS: Windows 10

Additionally, you can choose to provide more details, e.g. the output of:

- [Repository to help reproduce](https://github.com/Mangiang/objectbox_infection_issue)
  - it is a brand new project with only the folloing files modified `pubspec.yml`, `generated_plugin_registrant.cc`, `generated_plugin_registrant.cmake` (see commits on the repo)
- [VirusTotal report](https://www.virustotal.com/gui/file/e44b13cf2eb654ecc2e71838572b4de3faa6777620f11438c829e9d8f349cf4a?nocache=1)

### Steps to reproduce

1. Clone the repository
2. Execute `flutter pub get`
3. Execute `flutter run -d windows`
4. If no antivirus flagged `objectbox_flutter_libs_plugin.dll`, try to send it to VirusTotal for analysis
5. Notice either the Antivirus or VirusTotal report about a `Gen:Variant.Tedy.191479`

### Expected behavior

No virus should be detected when executing a brand new project using that package.

### Code

If applicable, add code to help explain your problem.

- `pubspec.yaml`
```yml
name: objectbox_infection_issue
description: Replication for Objectbox infection flagging issue

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true
```

### Logs, stack traces

[VirusTotal report](https://www.virustotal.com/gui/file/e44b13cf2eb654ecc2e71838572b4de3faa6777620f11438c829e9d8f349cf4a?nocache=1)

Bitdefender Report:
![image](https://user-images.githubusercontent.com/9913715/186779127-c361ade7-7a9b-43b0-93e4-70bee46f730a.png)
