### ISSUE TITLE
Can not load ToMany data content

### ISSUE THREAD

**Issue by ThatPham2000** [objectbox/objectbox-dart#655]
### Is there an existing issue?

No
- [ √ ] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Build info

- objectbox version: 4.0.1
- Flutter/Dart version: 3.22.2
- Build OS: macOS Ventura 13.6.1
- Deployment OS or device: Android 12 emulator

### Steps to reproduce

Just run this code.
<img width="442" alt="image" src="https://github.com/user-attachments/assets/044d347a-2b9f-4178-b5c4-117b8f82f45d">

### Expected behavior

I want "a" can access list of "c".

### Actual behavior

Get "c" from "a" is empty.

### Code

You can create a minimal package with e.g. `flutter create bug`.

Things you maybe should also include:
- the entity class: I want to save Id by my self.

```dart
import 'package:objectbox/objectbox.dart';

@Entity()
class A {
  A({required this.name}) {
    obId = name.hashCode;
  }

  @Id(assignable: true)
  int? obId;

  final String name;

  final b = ToOne<B>();
}

@Entity()
class B {
  B({required this.name2}) {
    obId = name2.hashCode;
  }

  @Id(assignable: true)
  int? obId;

  final String name2;

  final c = ToMany<C>();
}

@Entity()
class C {
  C({required this.name3}) {
    obId = name3.hashCode;
  }

  @Id(assignable: true)
  int? obId;

  final String name3;
}

```

- the pubspec.yaml

```yaml
name: object_box_to_many
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  path: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

You can also create a public GitHub repository and link to it below.

Please do not upload screenshots of text, use code blocks like below instead.

-->

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:object_box_to_many/model/object_box.dart';

import 'model/model.dart';

late ObjectBox objectbox;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  objectbox = await ObjectBox.create();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  
  final boxA = objectbox.store.box<A>();
  final boxB = objectbox.store.box<B>();
  final boxC = objectbox.store.box<C>();

  void _incrementCounter() {
    final a = A(name: 'name A');
    final b = B(name2: 'name B');
    final c = C(name3: 'name C');
    final c2 = C(name3: 'name C2');

    boxC.putMany([c,c2]);

    boxB.put(b);

    a.b.target = b;
    b.c.addAll([c, c2]);
    boxA.put(a);

    final aFromDb = boxA.getAll();
    final bFromA = aFromDb.first.b.target;
    final cFromB = bFromA!.c;

    final bFromDb = boxB.getAll();
    final cFromDb = boxC.getAll();

    
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Logs, stack traces

_TODO Add relevant logs, a stack trace or crash report._

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
