### ISSUE TITLE
ToMany relations are not updating when you put the parent entity

### ISSUE THREAD

**Issue by nickolasdeluca** [objectbox/objectbox-dart#679]
### Is there an existing issue?

- [X] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Build info

- objectbox version: 4.0.2
- Flutter/Dart version: 3.22.3
- Build OS: macOS 15.0.1
- Deployment OS or device: Both iOS 18 and Android 11

### Steps to reproduce

1. Create two classes that will be related to each other. MyOrder and MyItem could be the names. A MyOrder can have many MyItem.
2. Insert one MyOrder with one or more MyItem attached to it.
3. Edit one of the Items, change any of its properties and put the MyOrder object in order to update it.
4. Notice that the items are not updated, only MyOrder.

### Expected behavior

As specified on the method `applyToDb`, it'd expect it to automatically update the items, which were modified.

```
Saves changes (added and removed entities) made to this relation to the database. 
For some important details, see the notes about relations of [Box.put].

Note that this is called already when the object that contains this ToMany is put. 
However, if only this ToMany has changed, it is more efficient to just use this method.

Throws [StateError] if the object that contains this ToMany has no ID assigned (it must have been put before).
```

### Actual behavior

The items are not updated. Items can be added or removed, working just fine, but when updating, it doesn't work.

### Code
`order.dart`
```dart
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_playground/models/item.dart';

@Entity()
class MyOrder {
  @Id(assignable: false)
  int id;
  ToMany<Item> items = ToMany<Item>();
  double? total;

  MyOrder({
    this.id = 0,
    this.total,
  });

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};

    json['id'] = id;
    json['total'] = total;
    json['items'] = items.map((item) => item.toJson()).toList();

    return json;
  }
}
```
`item.dart`
```dart
import 'package:objectbox/objectbox.dart';

@Entity()
class Item {
  @Id(assignable: false)
  int id;
  String? name;
  double? price;
  double? quantity;
  double? total;

  Item({
    this.id = 0,
    this.name,
    this.price,
    this.quantity,
    this.total,
  });

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};

    json['id'] = id;
    json['name'] = name;
    json['price'] = price;
    json['quantity'] = quantity;
    json['total'] = total;

    return json;
  }
}
```
`pubspec.yaml`
```yaml
name: objectbox_playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  objectbox_generator: ^4.0.2

flutter:
  uses-material-design: true
```
`objectbox.dart`
```dart
import 'package:path/path.dart' as path;
import 'package:objectbox_playground/objectbox.g.dart';
import 'package:path_provider/path_provider.dart';

late ObjectBox objectBox;

class ObjectBox {
  late final Store store;

  ObjectBox._create(this.store);

  static Future<ObjectBox> create() async {
    final docsDir = await getApplicationDocumentsDirectory();

    final store = await openStore(
      directory: path.join(docsDir.path, 'objectbox.db'),
    );

    return ObjectBox._create(store);
  }
}
```
method to update the object
```dart
static Future<void> updateOrInsert({required MyOrder order}) async {
  final boxOrder = objectBox.store.box<MyOrder>();

  await boxOrder.putAsync(order);
}
```
### Logs, stack traces

No errors are thrown, it just simply doesn't update.

I even tried to manually call the `applyToDb` method, with its three modes `put`, `insert` and `update`.
