### ISSUE TITLE
Unsupported operation ObjectBox platform-specific library not compatible

### ISSUE THREAD

**Issue by jeremy-giles** [objectbox/objectbox-dart#690]
Hello, I can't understand why all morning I can build and launch our application on Android devices and how following a pull action from our git I have the error:

> I/flutter ( 6701): Unsupported operation: ObjectBox platform-specific library not compatible: is 4.0.0 (4.0.0-2024-05-14 (http, admin, lmdb, VectorSearch)), expected 4.0.1 (4.0.2-2024-10-15) or newer. For Flutter, check if the ObjectBox Pod or objectbox-android-objectbrowser need to be updated. For Dart, re-run the install.sh script to download the latest version.

NB: The problem is only in debug. The application built in release works...

pubspec.yaml
```
dependencies:
  
  flutter:
    sdk: flutter
  objectbox: ^4.0.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_generator: any
```

build.gradle
```
// Tell Gradle to exclude the objectbox-android dependency
// that is added by objectbox_flutter_libs for debug builds.
configurations {
    debugImplementation {
        exclude group: 'io.objectbox', module: 'objectbox-android'
    }
}

dependencies {
    // Add objectbox-android-objectbrowser only for debug builds.
    // Replace <version> with the included objectbox-android version,
    // e.g. check https://github.com/objectbox/objectbox-dart/releases
    // Warning: when ObjectBox for Dart updates check if <version>
    // needs to be updated.
    debugImplementation("io.objectbox:objectbox-android-objectbrowser:4.0.0")
}
```

**Comment by greenrobot-team** [comment]
> For Flutter, check if the ObjectBox Pod or objectbox-android-objectbrowser need to be updated.

In the `build.gradle` posted, update `objectbox-android-objectbrowser` to a supported release as noted in the comment.

**Comment by sadespresso** [comment]
Hello there! I'm having the same issue even tho I have set following:

```yaml filename="pubspec.yaml"
# pubspec.yaml

dependencies:
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
```

```gradle filename="app/build.gradle"
// app/build.gradle

configurations {
    debugImplementation {
        exclude group: 'io.objectbox', module: 'objectbox-android'
    }
}

dependencies {
    debugImplementation("io.objectbox:objectbox-android-objectbrowser:4.0.2")
}
```
